# Generated by Django 5.2.5 on 2025-08-28 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('DESCRIPCION', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dispositivo',
            old_name='consumo',
            new_name='consumo_maximo',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.categoria'),
            preserve_default=False,
        ),
    ]
