# Generated by Django 5.2.1 on 2025-08-29 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_categoria_rename_consumo_dispositivo_consumo_maximo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='DESCRIPCION',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='consumo_maximo',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='consumo_maximo_w',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='dispositivos.categoria'),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=255)),
                ('umbral_w', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo_registrado_w', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reconocida', models.BooleanField(default=False)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='dispositivos.dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='zona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='dispositivos', to='dispositivos.zona'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['categoria'], name='dispositivo_categor_e16198_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivo',
            index=models.Index(fields=['zona'], name='dispositivo_zona_id_cb0228_idx'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
