# Generated by Django 5.2.1 on 2025-08-29 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_zona_remove_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('consumo_w', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones', to='dispositivos.dispositivo')),
            ],
        ),
    ]
